# Generated by Django 5.0.5 on 2024-05-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_room_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="image_url",
            new_name="image_url_main",
        ),
        migrations.AddField(
            model_name="room",
            name="small_image_url_1",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="room",
            name="small_image_url_2",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="room",
            name="small_image_url_3",
            field=models.URLField(blank=True),
        ),
    ]
