# Generated by Django 5.0.5 on 2024-05-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_rename_image_url_room_image_url_main_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="room",
            name="price_per_night",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
